# Generated by Django 5.2 on 2026-02-16 15:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("organization", models.CharField(blank=True, max_length=200)),
                ("date", models.CharField(max_length=50)),
                ("icon", models.CharField(default="🏆", max_length=10)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institution", models.CharField(max_length=200)),
                ("degree", models.CharField(max_length=200)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField()),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=200)),
                ("github_link", models.URLField(blank=True)),
                ("linkedin_link", models.URLField(blank=True)),
                ("website_link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "image_icon",
                    models.CharField(
                        help_text="Emoji icon or FontAwesome class", max_length=10
                    ),
                ),
                (
                    "technologies",
                    models.CharField(
                        help_text="Comma separated list of technologies", max_length=500
                    ),
                ),
                ("link", models.URLField(blank=True)),
                (
                    "link_text",
                    models.CharField(blank=True, default="Website", max_length=50),
                ),
                ("order", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("authors", models.CharField(max_length=500)),
                ("journal", models.CharField(max_length=200)),
                ("date", models.CharField(max_length=50)),
                ("link", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[("TECH", "Technology"), ("LANG", "Language")],
                        default="TECH",
                        max_length=4,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["category", "order"],
            },
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("start_date", models.CharField(max_length=50)),
                ("end_date", models.CharField(max_length=50)),
                ("description", ckeditor.fields.RichTextField()),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-order"],
            },
        ),
    ]
