# Generated by Django 5.2 on 2026-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a project screenshot or cover image",
                null=True,
                upload_to="projects/",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="image_icon",
            field=models.CharField(
                blank=True, help_text="Emoji icon or FontAwesome class", max_length=10
            ),
        ),
    ]
