# Generated by Django 5.2 on 2026-02-17 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_image_alter_project_image_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="paper",
            field=models.FileField(
                blank=True,
                help_text="Upload the publication paper (PDF)",
                null=True,
                upload_to="publications/",
            ),
        ),
    ]
