# Generated by Django 5.2 on 2026-02-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_publication_paper"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workexperience",
            options={"ordering": ["order"]},
        ),
    ]
